# -*- coding: utf-8 -*-
"""test_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TfZkbcw8bh0iYOIOzpi0_VEA2ycp3xX-
"""

import time
import unittest

from faker import Faker
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

####################################   Sign_Up As Student   ########################
login_url = r'https://noureldin.pythonanywhere.com/campus_portal/student_signup'

First_Name = "Hussein"

Last_Name = "Elwakeel"
fake = Faker()



user_name = "Hussein_Elwakeel"

email = "hussein_m90388@cic-cairo.com"

password = "hussein12345"  # to send the password

retyped_password = "hussein12345"  # to send the password

phone_number = "01210247381"

birthdate = "17012001"


time.sleep(2)


class LoginTest(unittest.TestCase):
    def setUp(self):
        # basic things
        options = webdriver.ChromeOptions()
        options.headless = False
        # Start Chrome WebDriver
        self.service = ChromeService(executable_path=ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=self.service, options=options)
        self.driver.implicitly_wait(1)  # wait  to load the page
        self.driver.maximize_window()  # to max the window

    def test_signup_without_agree_terms_field(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        # self.agreeTerms_button = self.driver.find_element(By.XPATH,'//*[@id="agreeTerms"]')
        # self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_by_empty_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys('')

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys('')

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys('')

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys('')

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys('')

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys('')

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys('')

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys('')

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

        # self.time.sleep(2)

    def test_signup_with_one_has_register_fields(self):
        # should start with test
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_email_field(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_first_name_field(self):
        # should start with test
        self.driver.get(login_url)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_last_name_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_username_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_password_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_phone_number_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_birthdate_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_without_retype_password_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(user_name)

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(email)

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertEqual(login_url, self.driver.current_url)

    def test_signup_with_new_email_fields(self):
        # should start with test
        self.driver.get(login_url)

        self.first_name_field = self.driver.find_element(By.NAME, "first_name")
        self.first_name_field.send_keys(First_Name)

        self.last_name_field = self.driver.find_element(By.NAME, 'last_name')
        self.last_name_field.send_keys(Last_Name)

        self.username_field = self.driver.find_element(By.NAME, 'username')
        self.username_field.send_keys(fake.username())

        self.email_field = self.driver.find_element(By.NAME, 'email')
        self.email_field.send_keys(fake.email())

        self.password_field = self.driver.find_element(By.NAME, 'password')
        self.password_field.send_keys(password)

        self.retype_password_field = self.driver.find_element(By.NAME, 'retyped_password')
        self.retype_password_field.send_keys(retyped_password)

        self.phone_number_field = self.driver.find_element(By.NAME, 'phone_number')
        self.phone_number_field.send_keys(phone_number)

        self.birthdate_field = self.driver.find_element(By.NAME, 'birthdate')
        self.birthdate_field.send_keys(birthdate)

        self.agreeTerms_button = self.driver.find_element(By.XPATH, '//*[@id="agreeTerms"]')
        self.agreeTerms_button.click()

        self.register_button = self.driver.find_element(By.XPATH, '//*[@id="form"]/div[13]/div[2]/button')
        self.register_button.click()

        self.assertNotEqual(login_url, self.driver.current_url)

    def tearDown(self):
        # close the browser window
        self.driver.quit()


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)
